[loadbalancers]
node1 ansible_host=localhost ansible_port=2221

[dbservers]
node2 ansible_host=localhost ansible_port=2222

[multi_tier:children]
loadbalancers
dbservers

[all:vars]
ansible_user=root
ansible_python_interpreter=/usr/bin/python3
# Environment variable for all servers
env=development