---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin-credentials
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgCq1LC+Pm0U1Ufs+Mptck0OEDUP3/WNCLoZ4z0Ysjfs/qk3xljo59mQoUcA9k/qjcVu+LWTF9IDYYl3ppIuBw/WeXxUc8aB3EMDIPLeVd1Mo+p56bY7ujdtFWz5jfFG7plEZLg+ZAE1zVpMwrkLg2CzxOZ1VwHFwkPR4QHP+Yl2g1NyWUl+KB14P0vnKozwDHJ5H6ScQiVRdX/xQ8RuGfEASm8xqt5AW8GhiwjWlxrK+j2nryfMoMolbtcx8dzhdRG4Q+A11jRIEo7iLhm5O03Qi/r+4PvAmQC9oCWbLaboqS5AAN8iQ6mVhiAJvnbeWh5tXEylGVNhGoXjaUt3jun5NWdAjFcghqrhxKySvS06dtF3euJ187jp5Rn+TRs9T0LjL9FH0iful3QRCsXyMwU7aYFocE4GXvgEjxig7iLKiPytPuTeNxDdqVzA3nb4HFkBne+xqMmf9bXq5c7XzRgVriuVaafhXzg1CX4G4366duVQjFDggxCOp0IRVkeHhanpcwROKf1lb9zFm1GWYuPZs6yapRyhc3cY0MXWZzrvB0ni0XPz4NbwHyS/4u7ls4WmLBWS6k4rlLjFQ20swVBo1iTccMMXLgq93o1rlX2zDqqfPokJvhbMOixS0eHyK6pNAf5677RdzOGSsHnOt10F++rqaDfZu/6MrTW4iKZknfeCzUTItEpjBoYve3BQej8niq8bQg==
    admin-user: AgCczrWej54jyLPMCNlmLrKz68f6Doqdxn9vXEtzMZX5i4hMVFnKvLXqZv9abJE6vYzBpNP2iqhfkPCXnz3Br0rQyhxtBTwWVC6aSr0iXwbTKyux7EnKIPp1JZfigvgD7Z5Lgy56WiIgMkfuNW5iHsPHcATBBpbgjs+eggDDsHza5Si1r69K/bNoeDGUAyZFvB3kIGDrN9MEmCUPreXrwkPy9Ub6YXIv2QQRuoNXb4tiEmhWyZUWdoFCDbsLrGO1bhO7gPEBfucvtYCOe1cpzpZJlb35MZToRYnBS0wWo258s6AkA5/4uCPINLPzHbjGDwS53SMUucQBld0cyO+wMdWCDyjHAcPkoyMgax8HHwigVDCUGEiDhzPwNbzEUGIVjYYsTgBkjkgZ8UYJamRNd8tVgOV9IoA1Y2NS2/lGHXlSkMeXOJ416z12KeIxZLCSIn8nLskzOL2SdT7G8s8h8cLxytTxW1V9EBTwnrHvqLo9p7mew4C3yo3VHmLMS5LhirC1F3VbZFWNX99CXl0nRwPBvTa1AAOToxUbYew6kTNlPkRYsFgvdq2nY6rzlgLIKsPmC/IZbuAp8VCOMPESONcQ/la5Iq3mUO4H/DNId8W2mKgIqIag6L/J0D4l+tPnrASW61EjS1KE6JJgf7VTUHg9/cw1DzgFFSSWYOoP4gUVfqS08iw4PNgqK57CMkpc/XLi3+RaeQ==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin-credentials
      namespace: monitoring
    type: Opaque
