---
# Main entry point for our infrastructure configuration
- name: Deploy Web Infrastructure
  hosts: webservers
  gather_facts: yes
  
  # We can override role defaults here at the Play level
  #vars:
  #  web_page_title: "Overridden by Playbook!"

  roles:
    - webserver