apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
  namespace: ansible-lab
spec:
  # High Availability: We run 2 copies of the app
  replicas: 2
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
        - name: python-app
          # The exact image name and tag we built locally
          image: my-python-app:v1
          # CRITICAL for Kind: Do not try to pull from Docker Hub
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DB_HOST
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DB_NAME
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DB_USER
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: DB_PASS
          # Best Practice: Health Checks
          livenessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
          # Best Practice: Resource Limits
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: python-app-service
  namespace: ansible-lab
spec:
  selector:
    app: python-app
  type: NodePort # Expose port externally for testing
  ports:
    - protocol: TCP
      port: 80      # Port accessible inside the cluster
      targetPort: 5000 # Port the container listens on
      nodePort: 30000 # Fixed port to access from your laptop