---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: my-python-app-db-secret
  namespace: ansible-lab
spec:
  encryptedData:
    db-password: AgAf0QCOboPJnS26FsTTE2/c+YMYpbBgA5R00JKUZAfUICZFirqN1WWEa63q+mitiuoP5hvNLsgMwdn61xiTAwgzrGeMQeff8t3jblw6EnibIq3vyAOp+Sr4aqbJlmp9iS+hBRY/iVGx+qmiBOoQkTRDU3O3eJ12cEuMU/ycUYrK2xtNquTAwB6tm/NxLrBwau6wbi9ncT1/owTv2KQH32ESJGCMzKdnhXwul7BZOXXe5PQZSJl5iTxXOVTtnjhHAIZ1jXZU7w4CerUEvLGflC/ejrqRokBvnwvsgX9iI56KseGMvX5RxcyLuh3yFJWh6HVPcNtvUqQzK4+i2h2b5yCLv7SzFCWxB66ssIXC7mJA+qEJfImNZFqar7z+qKhRMdfe9qurxZIhkwSICr+ulYqDzKre96+/9Gk+XZ3Jslj7Gedk4eIuzEx6GJr4R576Zxq5s/Kx7SyJnfW28F2cTeq+94WMJuEq4sk+IS/hKgT2SXWGDl/z9lLSq1x2NR56E+2CShXpW6KM/r2w7y8gbGU1A76J0QRrmaF6BHvF/YaxVhH3TftnPOuCKzd4RcZjIKV1OsgS1LMcUgmJB6HOYtvqhWvniI5pc9iPm0rLUsEKU0mR+vdjtNCpkfwADvpihgIMw2df4wM/VLVFjpQAM49AQJy5GjX8Mp4npPr+0Sgpf3qUsURIEqOmW6kQs3tLnBkGNPih55PsbSgKDEezI+XZzpdO
  template:
    metadata:
      creationTimestamp: null
      name: my-python-app-db-secret
      namespace: ansible-lab
