---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: my-python-app-db-secret
  namespace: ansible-lab
spec:
  encryptedData:
    db-password: AgCjRvRJPzckee330Y2sDvjte1S1OxKwFyM/B2D7TUjhVrNV0+sTv0zuWoZSdc21sPMqv0YYiWQGNRNF1c+3VPECwA95teCEAoWSKzbhvWXUx1L2ntwnERfSSp+0QrT7FXFmy13f2GbyQcmDLBK34yQQ4v33wo/5aggNV91UiRV4UXhmcURJVCB8kFLygNv1JL4ie2BzoyPrWzfMzeAFlT6OAPumQb0KIc+rhYQM4SWqNnhBb0m3Ua0t4VNVDVA6BA3uV7C0vH49oXBD3ce+MhQ+GJeov4xTl51ImBXpg/suv5IZ3fskNPBvsxKw+cCiyXmwTrs6O3HIx/OTDVZBdAWxnNzvsanDlUU3WCk3e9nSTri1PgZnJaO5i61OLnNypL4Wjo4aCxkJ8n44dl3RnUFsG/DL5Dc8jxCH8IxPRrDktmKfYGiBQvvyo4Ep4o2lgiO/Ziky3e26lWipBLHlHFjjvYHHoj3ILEuYzcWgGKyTOaEi7Y4+0U/+eJKIXpSGeYB/MbR5fZtL6qsXxGa6arsgon5QbjfdaUdQLc4gGEAaRJydKlCFJJl+HI5dlLtM9KhgJGSA24VCbFdWYULIuJeO22q9cgTgntjpNEvW9hBFhu8s/A3Tb+GSuT2SwSQlNHf3AfGcAKCgdvSDWMZfzkemIvdmD0Sjh0Z8rX8Km8Eqj+TYKmXjcFld/ePX9PUOKXg3rj4/WrsRnJ/Jovfby+3B5bRN
  template:
    metadata:
      creationTimestamp: null
      name: my-python-app-db-secret
      namespace: ansible-lab
