---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: my-python-app-db-secret
  namespace: ansible-lab
spec:
  encryptedData:
    db-password: AgAaUfG5Na4xz543v0pKyoMmYq1b69dtoMy1rgqk+W8tQfGQmw3Dq0MzS0/ME8N7qSZ3WOxl8udlgJ5HK61IS4jHs0Y7JPCnVcnap3ZBS/lvPEc6WRXIgL7hwoPueHOp2WUpgsVQpo4swZmYYQanut5DTvsDe/5m8MNBmimZ7aYhFjXu/MxvFQ9HhTCEshUyF/OjPFCcklMSwUoMHKXvhE1pGZh7XLbrGAIwyw3EpT4UzvctFe8u7wO/1n/MRqSrkTo5QMrgvvrNcM6zV1KtC1rFQo6F3Uqegr4zna/XeYxRMDiuAWH3XQtprFWFpPNxcIahQjXF8bdYJMNKcji0VnDvYTYbS3rjoBoEepHZiCRecyzTmg7vs+Rjf4xqiD9b5NMZkGnCn7K90T2IVrjnLocVPa476HFJm8H4hmSToWqRKHRgdSG10wpxqzQkM+Hs1EkXdfkNpleo0AjSzN3Pa0SoBUehEklnx5TioTt36gUcxKiJU5xIyoeaWDg7OwSlXKk5DiHNfFCmWD/TfMqRLGngzldXEPG7d19GG9Fk0rz67n4PsNNgS2dtqC7fO5YrOpXgpfTaTPnSHoQi48SYQ/bIFyk8O3Ul/zeBEkSpQyJrM9GTZ4e3KoKSJmXVotgJZLipNoq31QSkrqaUqcK116uJNPKaIbbvI4EqOhmr2+frENIr5j6MzJhzrCytOP0AsVAyQGsPHeBN9NRj9Dbs3x2nPASa
  template:
    metadata:
      creationTimestamp: null
      name: my-python-app-db-secret
      namespace: ansible-lab
    type: Opaque
