apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-db-secret
  labels:
    app: {{ .Chart.Name }}
type: Opaque
data:
  # Helm function 'b64enc' automatically encodes the string to Base64
  # We access the variable from our passed secrets file
  db-password: {{ .Values.database.password | b64enc | quote }}