---
- name: Destroy Infrastructure
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - vars/gcp_config.yml

  tasks:
    - name: Destroy VM
      google.cloud.gcp_compute_instance:
        name: "{{ vm_name }}"
        zone: "{{ zone }}"
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_auth_kind }}"
        service_account_file: "{{ gcp_cred_file }}"
        state: absent

