---
# Playbook to configure a basic web server using Nginx
- name: Ensure Nginx is installed
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Ensure Nginx is running
  # Note: In some Docker containers without systemd, 
  # we use the service name directly.
  service:
    name: nginx
    state: started

# - name: Create a custom index.html
#   copy:
#     content: "<h1>Ansible is working on {{ ansible_facts['hostname'] }}</h1>"
#     dest: /var/www/html/index.html
#     owner: www-data
#     group: www-data
#     mode: '0644'

- name: Deploy dynamic index.html from template
  # The 'template' module processes Jinja2 files before sending them
  template:
    src: templates/index.html.j2
    dest: /var/www/html/index.html
    owner: www-data
    group: www-data
    mode: '0644'
  notify: restart nginx # This matches the name in handlers/main.yml