# Group of webservers managed by Ansible
[webservers]
node1 ansible_host=localhost ansible_port=2221
node2 ansible_host=localhost ansible_port=2222

# Global variables for all managed nodes
[all:vars]
# Use root user for SSH connection
ansible_user=root
# Explicitly define the Python interpreter to avoid version mismatches
ansible_python_interpreter=/usr/bin/python3